import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Cursor from "@/components/UI/Cursor";
import Provider from "@/components/Providers";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={font.className}
          style={{ backgroundColor: "var(--dark)" }}
        >
          <Navbar />
          <Cursor />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
